
import com.sun.awt.AWTUtilities;
import java.awt.AWTEventMulticaster;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gabriel Alvarado
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int x, y;

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        r_nombre = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        r_nickname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        r_contraC = new javax.swing.JPasswordField();
        r_contra = new javax.swing.JPasswordField();
        r_date = new com.toedter.calendar.JDateChooser();
        r_fecha = new javax.swing.JLabel();
        r_pais = new javax.swing.JComboBox();
        i_contra3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Imagen1 = new javax.swing.JLabel();
        VentanaUsuario = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_foto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        i_nombre = new javax.swing.JTextField();
        i_contraseña = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        i_contra = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Imagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        Registro.setMinimumSize(new java.awt.Dimension(525, 535));

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(525, 525));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(525, 525));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Nickname");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Contraseña");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Fecha");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 60, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Registrar Usuarios");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 40, 230, 50));

        label1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("Nombre");
        jPanel5.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Pais");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 80, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Confirmar");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 160, -1));

        jButton6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_grande.png"))); // NOI18N
        jButton6.setText("Registrar");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, -1));

        r_nombre.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        r_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r_nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(r_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 40));

        r_nickname.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        r_nickname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r_nickname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(r_nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 40));

        r_contraC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r_contraC.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        r_contraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_contraCActionPerformed(evt);
            }
        });
        jPanel5.add(r_contraC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, -1));

        r_contra.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        r_contra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        r_contra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel5.add(r_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 223, 180, 20));

        r_date.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(r_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 360, 180, -1));

        r_fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        jPanel5.add(r_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 40));

        r_pais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Honduras", "Guatemala", "Panama", "Salvador", "Nicaragua", "Estados Unidos", "Canada", "España", "Puerto Rico", " ", " " }));
        r_pais.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        r_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_paisActionPerformed(evt);
            }
        });
        jPanel5.add(r_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, 20));

        i_contra3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        i_contra3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        i_contra3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        jPanel5.add(i_contra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 40));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 40));

        Imagen1.setForeground(new java.awt.Color(255, 0, 0));
        Imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/500px-MIDNIGHT-BLUE.png"))); // NOI18N
        Imagen1.setOpaque(true);
        jPanel5.add(Imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 510));

        jTabbedPane2.addTab("Crear Usuario", jPanel5);

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VentanaUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Muro de usuario");
        VentanaUsuario.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Foto");
        VentanaUsuario.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lb_foto.setBackground(new java.awt.Color(255, 255, 255));
        lb_foto.setIcon(new javax.swing.ImageIcon("C:\\Users\\Gabriel Alvarado\\Desktop\\Imagenes\\Proyecto\\fondo-blanco-de-la-pared-de-ladrillo_1372-478.jpg")); // NOI18N
        VentanaUsuario.getContentPane().add(lb_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 210));

        jButton1.setText("Seleccionar foto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        VentanaUsuario.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        VentanaUsuario.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 400, 290));

        jButton5.setText("Agregar foto");
        VentanaUsuario.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jButton2.setText("Agregar publicacion");
        VentanaUsuario.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        Img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoAzul.png"))); // NOI18N
        Img.setText("jLabel6");
        VentanaUsuario.getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 480));

        jMenu1.setText("File");

        jMenuItem1.setText("Muro General");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Mensajes");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Lista amigos");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Calendario");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        VentanaUsuario.setJMenuBar(jMenuBar1);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(525, 535));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        i_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        i_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(i_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 20));

        i_contraseña.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        i_contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        i_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i_contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(i_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 180, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linea.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, 20));

        i_contra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        getContentPane().add(i_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/txt_med.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 80, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Inicio de Sesion");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 250, -1));

        jButton4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_grande.png"))); // NOI18N
        jButton4.setText("Registro");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 140, -1));

        jButton3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_grande.png"))); // NOI18N
        jButton3.setText("Login");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setHideActionText(true);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 200, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar_32px.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 40, 40));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/500px-ALIZARIN.png"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 590));

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void i_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_nombreActionPerformed

    private void i_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_i_contraseñaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        for (Usuario t : ListUsuarios) {
           
         if (t.getNickname().equals(i_nombre.getText()) && t.getContrasena().equals(i_contraseña.getText())) {
            
               VentanaUser q = new VentanaUser();
               q.pack();
               q.setLocationRelativeTo(this);
               q.setVisible(true);
                JOptionPane.showMessageDialog(this.VentanaUsuario, "Bienvenido"+t.getNickname());
                
            } else {
                JOptionPane.showMessageDialog(this, "El usuario o contraseña es incorrecta");
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        Registro.pack();
        Registro.setModal(true);
        Registro.setVisible(true);
        Registro.setLocationRelativeTo(this);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    String nombre="",nickname="",contra="",contraC ="",pais="";
    String fecha;
     BaseDeDatos bd = new BaseDeDatos();
            bd.conectar();
        try {
            nombre = r_nombre.getText();
            nickname = r_nickname.getText();
            contra = r_contra.getText();
            contraC = r_contraC.getText();
            pais = (r_pais.getSelectedItem()).toString();
            fecha = (r_date.getDate()).toString();
            if (r_contra.getText().equalsIgnoreCase(contraC)) {
                
                ListUsuarios.add(new Usuario(nombre, nickname, contra, pais, fecha));
                bd.query.execute("INSERT INTO USUARIO"
                        + " (NOMBRE,USUARIO, CLAVE, PAIS,FECHA) "
                        + " VALUES (('" + r_nombre + "','" + r_nickname + "','" + r_contra + "','" + r_pais +"','"+ r_fecha+ "')");
                bd.commit();
               
            }else{
                JOptionPane.showMessageDialog(this.Registro, "Las contraseñas no coinciden");
            }
            
        } catch (SQLException e) {
              JOptionPane.showMessageDialog(this, "ERROR EN CREAR USUARIO");
                System.out.println(e);
            }
            bd.desconectar();
             //setear
                r_nombre.setText("");
                r_nickname.setText("");
                r_contra.setText("");
                r_contraC.setText("");
                r_fecha.setText("");
          
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void r_contraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_contraCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_contraCActionPerformed

    private void r_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_paisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();

            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.lb_foto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                }
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel Imagen1;
    private javax.swing.JLabel Img;
    private javax.swing.JDialog Registro;
    private javax.swing.JDialog VentanaUsuario;
    private javax.swing.JLabel i_contra;
    private javax.swing.JLabel i_contra3;
    private javax.swing.JPasswordField i_contraseña;
    private javax.swing.JTextField i_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JPasswordField r_contra;
    private javax.swing.JPasswordField r_contraC;
    private com.toedter.calendar.JDateChooser r_date;
    private javax.swing.JLabel r_fecha;
    private javax.swing.JTextField r_nickname;
    private javax.swing.JTextField r_nombre;
    private javax.swing.JComboBox r_pais;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> ListUsuarios = new ArrayList();
 ArrayList<Usuario> ListMensajes = new ArrayList();
}
